---
- name: Include OS specific variables
  include_vars: "os_family_{{ ansible_os_family|lower }}.yml"

- name: Install samba packages
  package:
    name:
      - samba
      - samba-client
      - samba-common
      - cifs-utils
    state: present

- name: Update smb.conf
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart samba service

- name: Enable and start samba service
  ansible.builtin.service:
    name: "{{ samba_daemon }}"
    state: started
    enabled: true
